// ═══════════════════════════════════════════════════════════════════
// INTEGRATION TESTS — Import → Fix Name Mismatches → Records → All Tabs
// Tests the FULL user journey after file import
// ═══════════════════════════════════════════════════════════════════
function normalizeName(raw){if(!raw)return"";var s=String(raw).trim().toLowerCase().replace(/[^a-z ]/g," ");var t=s.split(/\s+/).filter(x=>x.length>0);var m=[],i=0;while(i<t.length){if(t[i].length===1){var g="";while(i<t.length&&t[i].length===1)g+=t[i++];m.push(g);}else m.push(t[i++]);}return m.filter(p=>p.length>1).sort().join(" ");}
function editDistance(a,b){if(a===b)return 0;var la=a.length,lb=b.length;if(!la)return lb;if(!lb)return la;var dp=Array.from({length:lb+1},(_,j)=>j);for(var ii=1;ii<=la;ii++){var nd=[ii];for(var j=1;j<=lb;j++)nd[j]=Math.min(nd[j-1]+1,dp[j]+1,dp[j-1]+(a[ii-1]===b[j-1]?0:1));dp=nd;}return dp[lb];}
function tokensFormCompound(tok,comp){if(!tok.every(t=>comp.indexOf(t)!==-1))return false;var tmp=comp,st=tok.slice().sort((a,b)=>comp.indexOf(a)-comp.indexOf(b));for(var t of st){var ix=tmp.indexOf(t);if(ix===-1)return false;tmp=tmp.slice(0,ix)+"_".repeat(t.length)+tmp.slice(ix+t.length);}return tok.reduce((s,t)=>s+t.length,0)>=comp.length*0.85;}
function fuzzyMatchScore(a,b){var na=normalizeName(a),nb=normalizeName(b);if(!na||!nb)return 0;if(na===nb)return 1.0;var ta=na.split(" "),tb=nb.split(" "),sa={},sb={};ta.forEach(t=>sa[t]=1);tb.forEach(t=>sb[t]=1);var sc=[];var iAB=ta.filter(t=>sb[t]).length,iBA=tb.filter(t=>sa[t]).length;if(iAB===ta.length||iBA===tb.length)sc.push(0.85+Math.min(ta.length,tb.length)/Math.max(ta.length,tb.length)*0.1);var nas=na.replace(/ /g,""),nbs=nb.replace(/ /g,"");if(nas===nbs)return 0.95;if(ta.length>1&&tokensFormCompound(ta,nbs))sc.push(0.92);if(tb.length>1&&tokensFormCompound(tb,nas))sc.push(0.92);var inter=ta.filter(t=>sb[t]);if(inter.length)sc.push(Math.max(inter.length/(ta.length+tb.length-inter.length),inter.length/Math.min(ta.length,tb.length)*0.85));sc.push((1-editDistance(na,nb)/Math.max(na.length,nb.length,1))*0.95);sc.push((1-editDistance(nas,nbs)/Math.max(nas.length,nbs.length,1))*0.95);var best=Math.max(...sc,0);if(best<0.7&&inter.length===1&&inter[0].length<=3)best=Math.min(best,0.45);return best;}
function getSeverity(u){const e=Number(u.entered)||0,s=Number(u.scheduled)||0;if(s===0||e>=s)return 0;if(e===0)return 4;const g=((s-e)/s)*100;if(g<=10)return 1;if(g<=30)return 2;if(g<=60)return 3;return 4;}
function getStatus(u){var e=Number(u.entered)||0,s=Number(u.scheduled)||0;if(!s)return"purple";if(e===0)return"red";if(e>=s)return"green";return"yellow";}
function mergeRecords(ibm,clarity,manual){manual=manual||{};var cmap={};clarity.forEach(r=>cmap[r.normalizedName]=r);var matched=[],ibmOnly=[],clarityOnly=[],used={};function build(i,c){return{id:i.normalizedName,name:i.rawName,normalizedName:i.normalizedName,clarityName:c?c.rawName:null,scheduledHours:i.scheduledHours||0,actualHours:c?c.actualHours:0,monthlyHours:c?c.monthlyHours||{}:{},ibmMonthlyHours:i.ibmMonthlyHours||{},timesheetStatus:c?c.timesheetStatus:"Not in Clarity",resourceManager:c?c.resourceManager:"",periods:c?c.periods||[]:[],clarityPeriods:c?c.periods||[]:[],workitems:i.workitems||[],claimMonths:i.claimMonths||[],weeklyBreakdown:i.weeklyBreakdown||[],dayHours:i.dayHours||{},dataSource:c?"Both":"IBM only",matched:!!c,wbsId:i.wbsId||"",billingCode:i.billingCode||"",country:i.country||"",talentId:i.talentId||""};}ibm.forEach(function(i){var c=cmap[i.normalizedName];if(c){used[i.normalizedName]=true;matched.push(build(i,c));return;}var mk=manual[i.normalizedName];if(mk&&cmap[mk]){used[mk]=true;matched.push(build(i,cmap[mk]));return;}var best=0,bc=null,bk=null;clarity.forEach(function(cr){if(used[cr.normalizedName])return;var sc=fuzzyMatchScore(i.rawName,cr.rawName);if(sc>best){best=sc;bc=cr;bk=cr.normalizedName;}});if(best>=0.85&&bc){used[bk]=true;matched.push(build(i,bc));return;}ibmOnly.push(build(i,null));});clarity.forEach(function(c){if(!used[c.normalizedName])clarityOnly.push({id:c.normalizedName,name:c.rawName,normalizedName:c.normalizedName,clarityName:c.rawName,scheduledHours:0,actualHours:c.actualHours||0,monthlyHours:c.monthlyHours||{},timesheetStatus:c.timesheetStatus,resourceManager:c.resourceManager,periods:c.periods||[],clarityPeriods:c.periods||[],workitems:[],claimMonths:[],weeklyBreakdown:[],dayHours:{},dataSource:"Clarity only",matched:false,wbsId:"",billingCode:"",country:"",talentId:""});});return{matched,ibmOnly,clarityOnly};}
function handleImport(data){return data.map(function(r){return{id:r.id||r.normalizedName,normalizedName:r.normalizedName||r.id||"",name:r.name,clarityName:r.clarityName||null,email:r.email||"",dept:r.country||"Imported",resourceManager:r.resourceManager||"--",scheduled:r.scheduledHours||0,entered:r.actualHours||0,lastEntry:r.periods&&r.periods.length?r.periods[r.periods.length-1]:null,projects:r.workitems?r.workitems.slice(0,3).map((w,i)=>({code:"WI-"+(i+1),name:w})):[],weeklyBreakdown:r.weeklyBreakdown||[],clarityPeriods:r.clarityPeriods||r.periods||[],activityCode:r.activityCode||"",monthlyHours:r.monthlyHours||{},ibmMonthlyHours:r.ibmMonthlyHours||{},sourceMonths:r.sourceMonths||[],talentId:r.talentId||"",serialId:r.serialId||"",country:r.country||"",billingCode:r.billingCode||"",wbsId:r.wbsId||"",claimMonths:r.claimMonths||[],timesheetStatus:r.timesheetStatus||"",approvedBy:r.approvedBy||"",resourceActive:r.resourceActive||"",periods:r.periods||[],dayHours:r.dayHours||{},dataSource:r.matched?"Both":(r.scheduledHours>0?"IBM only":"Clarity only"),history:[],monthlyEntries:{}};});}
function applyLinks(users,linked,clarityPool){var next=users.slice(),toRemove={};linked.forEach(function(link){var ibmIdx=next.findIndex(u=>u&&u.id===link.ibmId);if(ibmIdx===-1)return;var ibm=next[ibmIdx];if(!ibm)return;var cd=clarityPool.find(c=>c.id===link.clarityId);if(!cd){var cu=next.find(u=>u&&u.id===link.clarityId);if(cu)cd={id:cu.id,name:cu.name,clarityName:cu.clarityName||cu.name,entered:cu.entered||0,monthlyHours:cu.monthlyHours||{},timesheetStatus:cu.timesheetStatus||"",resourceManager:cu.resourceManager||"",approvedBy:cu.approvedBy||"",resourceActive:cu.resourceActive||"",periods:cu.periods||[],clarityPeriods:cu.clarityPeriods||[]};}if(!cd)return;next[ibmIdx]=Object.assign({},ibm,{clarityName:cd.clarityName||cd.name,entered:cd.entered||0,actualHours:cd.entered||0,monthlyHours:cd.monthlyHours||{},timesheetStatus:cd.timesheetStatus||ibm.timesheetStatus,resourceManager:cd.resourceManager||ibm.resourceManager,approvedBy:cd.approvedBy||ibm.approvedBy,resourceActive:cd.resourceActive||ibm.resourceActive||"",periods:cd.periods||ibm.periods||[],clarityPeriods:cd.clarityPeriods||cd.periods||[],dataSource:"Both",lastEntry:(cd.periods&&cd.periods.length)?cd.periods[cd.periods.length-1]:ibm.lastEntry});toRemove[link.clarityId]=true;});return next.filter(u=>u&&!toRemove[u.id]);}
function filterUsers(users,opts){opts=opts||{};var fs=opts.filterStatus||"all",fc=opts.filterSource||"all",q=(opts.search||"").toLowerCase(),sm=opts.sortMode||"severity-desc";var l=users.filter(function(u){if(!u||!u.name)return false;if(fs!=="all"&&getStatus(u)!==fs)return false;if(fc!=="all"&&u.dataSource!==fc)return false;if(q&&!((u.name||"").toLowerCase().includes(q)||(u.clarityName||"").toLowerCase().includes(q)))return false;return true;});if(sm==="name")l=l.slice().sort((a,b)=>(a.name||"").localeCompare(b.name||""));if(sm==="severity-desc")l=l.slice().sort((a,b)=>getSeverity(b)-getSeverity(a));return l;}

let passed=0,failed=0,total=0;const results=[],sects=[];let sect="";
function section(n){sect=n;sects.push(n);}
function test(name,fn){total++;try{fn();passed++;results.push({s:sect,status:"PASS",name});}catch(e){failed++;results.push({s:sect,status:"FAIL",name,error:e.message});}}
function expect(val){return{toBe:e=>{if(val!==e)throw new Error(`Expected ${JSON.stringify(e)}, got ${JSON.stringify(val)}`);},toBeGreaterThan:e=>{if(!(val>e))throw new Error(`${val} not > ${e}`);},toBeGreaterThanOrEqual:e=>{if(!(val>=e))throw new Error(`${val} not >= ${e}`);},toBeLessThan:e=>{if(!(val<e))throw new Error(`${val} not < ${e}`);},toBeTruthy:()=>{if(!val)throw new Error(`Expected truthy, got ${JSON.stringify(val)}`);},toBeFalsy:()=>{if(val)throw new Error(`Expected falsy, got ${JSON.stringify(val)}`);},toBeNull:()=>{if(val!==null)throw new Error(`Expected null, got ${JSON.stringify(val)}`);},not:{toBe:e=>{if(val===e)throw new Error(`Expected NOT ${JSON.stringify(e)}`);},toBeNull:()=>{if(val===null)throw new Error("Expected NOT null");}}};}

const IBM_RAW=[
  {rawName:"Keerti Pujari",   normalizedName:normalizeName("Keerti Pujari"),   scheduledHours:171,wbsId:"DGSPQC-GBS",workitems:["BMO AML"], claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":171},weeklyBreakdown:[],dayHours:{},country:"India",   billingCode:"FC01",talentId:"T001"},
  {rawName:"Abdel Cervantes", normalizedName:normalizeName("Abdel Cervantes"), scheduledHours:189,wbsId:"DGSPQC-GBS",workitems:["BMO AML"], claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":189},weeklyBreakdown:[],dayHours:{},country:"Canada",  billingCode:"FC02",talentId:"T002"},
  {rawName:"Ayan Das",        normalizedName:normalizeName("Ayan Das"),        scheduledHours:88, wbsId:"DGSPQC-GBS",workitems:["BMO AML"], claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":88}, weeklyBreakdown:[],dayHours:{},country:"India",   billingCode:"FC03",talentId:"T003"},
  {rawName:"Kabil Ravi",      normalizedName:normalizeName("Kabil Ravi"),      scheduledHours:30, wbsId:"DGSPQC-GBS",workitems:["BMO Corp"],claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":30}, weeklyBreakdown:[],dayHours:{},country:"Canada",  billingCode:"FC04",talentId:"T004"},
  {rawName:"Ankita Singh",    normalizedName:normalizeName("Ankita Singh"),    scheduledHours:189,wbsId:"DGSPQC-GBS",workitems:["BMO AML"], claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":189},weeklyBreakdown:[],dayHours:{},country:"India",   billingCode:"FC05",talentId:"T005"},
  {rawName:"Devang Trivedi",  normalizedName:normalizeName("Devang Trivedi"),  scheduledHours:88, wbsId:"DGSPQC-GBS",workitems:["BMO AML"], claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":88}, weeklyBreakdown:[],dayHours:{},country:"India",   billingCode:"FC06",talentId:"T006"},
  {rawName:"Jomille Castro",  normalizedName:normalizeName("Jomille Castro"),  scheduledHours:36, wbsId:"DGSPQC-GBS",workitems:["BMO Corp"],claimMonths:["March-2026"],ibmMonthlyHours:{"March-2026":36}, weeklyBreakdown:[],dayHours:{},country:"Philippines",billingCode:"FC07",talentId:"T007"},
];
const CLARITY_RAW=[
  {rawName:"Pujari, Keerti",     normalizedName:normalizeName("Pujari, Keerti"),     actualHours:171,monthlyHours:{"March-2026":171},timesheetStatus:"Posted",   resourceManager:"Kanwal Sethi",  periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Cervantes, Abdel",   normalizedName:normalizeName("Cervantes, Abdel"),   actualHours:189,monthlyHours:{"March-2026":189},timesheetStatus:"Posted",   resourceManager:"Kanwal Sethi",  periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Das, Sayan",         normalizedName:normalizeName("Das, Sayan"),         actualHours:189,monthlyHours:{"March-2026":189},timesheetStatus:"Posted",   resourceManager:"Prasun Ghosal", periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Das, Ayan",          normalizedName:normalizeName("Das, Ayan"),          actualHours:88, monthlyHours:{"March-2026":88}, timesheetStatus:"Posted",   resourceManager:"Prasun Ghosal", periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Singh, Ankita2",     normalizedName:normalizeName("Singh, Ankita2"),     actualHours:189,monthlyHours:{"March-2026":189},timesheetStatus:"Posted",   resourceManager:"Dipak Vyas",    periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Castro, Jomille",    normalizedName:normalizeName("Castro, Jomille"),    actualHours:36, monthlyHours:{"March-2026":36}, timesheetStatus:"Posted",   resourceManager:"Abu Mohsin",    periods:["01-MAR-2026 to 15-MAR-2026","16-MAR-2026 to 31-MAR-2026"]},
  {rawName:"Bhashyam, Saisruthi",normalizedName:normalizeName("Bhashyam, Saisruthi"),actualHours:176,monthlyHours:{"March-2026":176},timesheetStatus:"Posted",   resourceManager:"Richard Ostafin",periods:["01-MAR-2026 to 15-MAR-2026"]},
];
const SAVED_CLARITY=CLARITY_RAW.map(c=>({id:c.normalizedName,name:c.rawName,clarityName:c.rawName,entered:c.actualHours||0,monthlyHours:c.monthlyHours||{},timesheetStatus:c.timesheetStatus||"",resourceManager:c.resourceManager||"",periods:c.periods||[],clarityPeriods:c.periods||[]}));
var merged0=mergeRecords(IBM_RAW,CLARITY_RAW,{});
var USERS=handleImport(merged0.matched.concat(merged0.ibmOnly).concat(merged0.clarityOnly));

section("1. Import Pipeline");
test("mergeRecords: no undefined records",()=>{[...merged0.matched,...merged0.ibmOnly,...merged0.clarityOnly].forEach((u,i)=>{if(!u||!u.id||!u.name)throw new Error(`Record[${i}] invalid`);});});
test("mergeRecords: counts add up",()=>{if(merged0.matched.length+merged0.ibmOnly.length!==IBM_RAW.length)throw new Error("IBM count mismatch");if(merged0.matched.length+merged0.clarityOnly.length!==CLARITY_RAW.length)throw new Error("Clarity count mismatch");});
test("handleImport: all required fields present",()=>{var F=["id","normalizedName","name","scheduled","entered","dataSource","projects","weeklyBreakdown","periods","clarityPeriods","monthlyHours","claimMonths","history","monthlyEntries"];USERS.forEach(u=>{F.forEach(f=>{if(u[f]===undefined)throw new Error(u.name+" missing "+f);});});});
test("handleImport: all array fields are arrays",()=>{var A=["projects","weeklyBreakdown","periods","clarityPeriods","claimMonths","history"];USERS.forEach(u=>{A.forEach(f=>{if(!Array.isArray(u[f]))throw new Error(u.name+"."+f+" not array");});});});
test("handleImport: monthlyEntries is plain object",()=>{USERS.forEach(u=>{if(typeof u.monthlyEntries!=="object"||Array.isArray(u.monthlyEntries))throw new Error(u.name+".monthlyEntries wrong type");});});
test("handleImport: normalizedName always string",()=>{USERS.forEach(u=>{if(typeof u.normalizedName!=="string")throw new Error(u.name+" normalizedName not string");});});
test("handleImport: dataSource always valid",()=>{var V=["Both","IBM only","Clarity only"];USERS.forEach(u=>{if(!V.includes(u.dataSource))throw new Error(u.name+" invalid dataSource: "+u.dataSource);});});
test("handleImport: no null records",()=>{USERS.forEach((u,i)=>{if(!u)throw new Error("USERS["+i+"] is null");});});
test("savedClarityRecs: 7 entries",()=>{if(SAVED_CLARITY.length!==7)throw new Error("Expected 7 got "+SAVED_CLARITY.length);});
test("savedClarityRecs: all have id+name",()=>{SAVED_CLARITY.forEach(c=>{if(!c.id||!c.name)throw new Error("Missing id/name: "+JSON.stringify(c));});});

section("2. Fix Name Mismatches - Clarity Pool");
test("savedClarityRecs >= clarityOnly users",()=>{expect(SAVED_CLARITY.length).toBeGreaterThanOrEqual(USERS.filter(u=>u.dataSource==="Clarity only").length);});
test("Das,Ayan scores higher than Das,Sayan for Ayan Das",()=>{expect(fuzzyMatchScore("Ayan Das","Das, Ayan")).toBeGreaterThan(fuzzyMatchScore("Ayan Das","Das, Sayan"));});
test("fuzzy top match for Ayan Das is Das,Ayan",()=>{var sc=SAVED_CLARITY.map(c=>({name:c.name,score:fuzzyMatchScore("Ayan Das",c.clarityName||c.name)})).sort((a,b)=>b.score-a.score);if(sc[0].name!=="Das, Ayan")throw new Error("Top match is "+sc[0].name+" not Das, Ayan");});
test("savedClarityRecs visible when all users are Both",()=>{var allBoth=USERS.map(u=>Object.assign({},u,{dataSource:"Both"}));expect(allBoth.filter(u=>u.dataSource==="Clarity only").length).toBe(0);expect(SAVED_CLARITY.length).toBe(7);});
test("clarityPool normalized shape valid",()=>{SAVED_CLARITY.forEach(c=>{if(!c.id)throw new Error("Missing id");if(!c.name)throw new Error("Missing name");if(c.entered===undefined)throw new Error("Missing entered");if(!Array.isArray(c.periods))throw new Error("periods not array");});});

section("3. applyLinks - Splice Bug Fix");
test("applyLinks: empty linked → same users",()=>{var r=applyLinks(USERS,[],SAVED_CLARITY);if(r.length!==USERS.length)throw new Error("Length changed with empty linked");});
test("applyLinks: single link → no undefined",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var r=applyLinks(USERS,[{ibmId:ibm.id,clarityId:SAVED_CLARITY[0].id}],SAVED_CLARITY);r.forEach((u,i)=>{if(!u||!u.id||!u.name)throw new Error("result["+i+"] invalid");});});
test("applyLinks: 3 links at once → no splice crash",()=>{var ibmList=USERS.filter(u=>u.dataSource==="IBM only").slice(0,3);if(!ibmList.length)return;var linked=ibmList.map((u,i)=>({ibmId:u.id,clarityId:SAVED_CLARITY[i%SAVED_CLARITY.length].id}));var err=null,r;try{r=applyLinks(USERS,linked,SAVED_CLARITY);}catch(e){err=e;}if(err)throw err;r.forEach((u,i)=>{if(!u)throw new Error("result["+i+"] undefined -- SPLICE BUG");});});
test("applyLinks: linked IBM record becomes Both",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var r=applyLinks(USERS,[{ibmId:ibm.id,clarityId:SAVED_CLARITY[0].id}],SAVED_CLARITY);expect(r.find(u=>u.id===ibm.id).dataSource).toBe("Both");});
test("applyLinks: clarity data transferred to IBM record",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var cl=SAVED_CLARITY[0];var r=applyLinks(USERS,[{ibmId:ibm.id,clarityId:cl.id}],SAVED_CLARITY);var u=r.find(x=>x.id===ibm.id);if(u.entered!==cl.entered)throw new Error("entered not transferred");});
test("applyLinks: clarityOnly user removed after linking",()=>{var co=USERS.find(u=>u.dataSource==="Clarity only");var io=USERS.find(u=>u.dataSource==="IBM only");if(!co||!io)return;var cl=SAVED_CLARITY.find(c=>c.id===co.id)||SAVED_CLARITY[0];var r=applyLinks(USERS,[{ibmId:io.id,clarityId:cl.id}],SAVED_CLARITY);if(r.find(u=>u.id===co.id))throw new Error("Clarity only user not removed");});
test("applyLinks: no undefined holes (filter not splice)",()=>{var ibmList=USERS.filter(u=>u.dataSource==="IBM only");var linked=ibmList.map((u,i)=>({ibmId:u.id,clarityId:SAVED_CLARITY[i%SAVED_CLARITY.length].id}));var r=applyLinks(USERS,linked,SAVED_CLARITY);var undefs=r.filter(u=>!u);if(undefs.length>0)throw new Error(undefs.length+" undefined holes found");});
test("applyLinks: nonexistent clarityId safe",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var err=null;try{applyLinks(USERS,[{ibmId:ibm.id,clarityId:"nonexistent_xyz"}],SAVED_CLARITY);}catch(e){err=e;}if(err)throw err;});
test("applyLinks: nonexistent ibmId safe",()=>{var err=null;try{applyLinks(USERS,[{ibmId:"nonexistent_ibm",clarityId:SAVED_CLARITY[0].id}],SAVED_CLARITY);}catch(e){err=e;}if(err)throw err;});
test("applyLinks: result count correct",()=>{var co=USERS.filter(u=>u.dataSource==="Clarity only");var io=USERS.filter(u=>u.dataSource==="IBM only");var n=Math.min(co.length,io.length);if(!n)return;var savedCl=co.map(u=>({id:u.id,name:u.name,clarityName:u.clarityName||u.name,entered:u.entered||0,monthlyHours:u.monthlyHours||{},timesheetStatus:u.timesheetStatus||"",resourceManager:u.resourceManager||"",approvedBy:"",resourceActive:"",periods:u.periods||[],clarityPeriods:u.clarityPeriods||[]}));var linked=io.slice(0,n).map((u,i)=>({ibmId:u.id,clarityId:savedCl[i].id}));var r=applyLinks(USERS,linked,savedCl);if(r.length!==USERS.length-n)throw new Error("Expected "+(USERS.length-n)+" got "+r.length);});

section("4. Records Tab Render Safety");
test("filterUsers: no crash",()=>{var err=null;try{filterUsers(USERS);}catch(e){err=e;}if(err)throw err;});
test("filterUsers: all results valid",()=>{filterUsers(USERS).forEach((u,i)=>{if(!u||!u.name||!u.id)throw new Error("filtered["+i+"] invalid");});});
test("filterUsers: getStatus safe on all",()=>{USERS.forEach(u=>{try{getStatus(u);}catch(e){throw new Error("getStatus failed "+u.name+": "+e.message);}});});
test("filterUsers: getSeverity safe on all",()=>{USERS.forEach(u=>{try{getSeverity(u);}catch(e){throw new Error("getSeverity failed "+u.name+": "+e.message);}});});
test("filterUsers: after applyLinks renderable",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var after=applyLinks(USERS,[{ibmId:ibm.id,clarityId:SAVED_CLARITY[0].id}],SAVED_CLARITY);var err=null;try{filterUsers(after);}catch(e){err=e;}if(err)throw err;filterUsers(after).forEach((u,i)=>{if(!u||!u.name)throw new Error("after-fix filtered["+i+"] invalid");});});
test("filterUsers: filterSource IBM only correct",()=>{filterUsers(USERS,{filterSource:"IBM only"}).forEach(u=>{if(u.dataSource!=="IBM only")throw new Error("Wrong source: "+u.dataSource);});});
test("filterUsers: filterSource Both correct",()=>{filterUsers(USERS,{filterSource:"Both"}).forEach(u=>{if(u.dataSource!=="Both")throw new Error("Wrong source: "+u.dataSource);});});
test("filterUsers: filterStatus green correct",()=>{filterUsers(USERS,{filterStatus:"green"}).forEach(u=>{if(getStatus(u)!=="green")throw new Error("Not green: "+u.name);});});
test("filterUsers: filterStatus red correct",()=>{filterUsers(USERS,{filterStatus:"red"}).forEach(u=>{if(getStatus(u)!=="red")throw new Error("Not red: "+u.name);});});
test("filterUsers: name search works",()=>{var r=filterUsers(USERS,{search:"keerti"});if(r.length>0){r.forEach(u=>{if(!(u.name||"").toLowerCase().includes("keerti")&&!(u.clarityName||"").toLowerCase().includes("keerti"))throw new Error("Search result wrong: "+u.name);});}});
test("filterUsers: sort name no crash with nulls",()=>{var mixed=USERS.concat([{id:"n1",name:null,dataSource:"Both",scheduled:0,entered:0}]);var err=null;try{filterUsers(mixed,{sortMode:"name"});}catch(e){err=e;}if(err)throw err;});
test("filterUsers: severity sort no crash",()=>{var err=null;try{filterUsers(USERS,{sortMode:"severity-desc"});}catch(e){err=e;}if(err)throw err;});
test("filterUsers: unique IDs in result",()=>{var r=filterUsers(USERS);var ids=r.map(u=>u.id);if(new Set(ids).size!==ids.length)throw new Error("Duplicate IDs in filtered result");});

section("5. EmployeeDetailPanel Safety");
test("DetailPanel: find every user by id",()=>{USERS.forEach(u=>{if(!USERS.find(x=>x.id===u.id))throw new Error("Cannot find "+u.name);});});
test("DetailPanel: missing id returns null",()=>{if(USERS.find(u=>u.id==="missing_xyz")||null)throw new Error("Should be null");});
test("DetailPanel: avatar initials safe",()=>{USERS.forEach(u=>{try{(u.name||"?").split(" ").map(n=>n[0]).join("");}catch(e){throw new Error("Avatar failed: "+u.name);}});});
test("DetailPanel: periods guard safe",()=>{USERS.map(u=>Object.assign({},u,{periods:undefined})).forEach(u=>{try{var s=u.wbsId||(u.periods&&u.periods.length>0);}catch(e){throw new Error("periods guard failed: "+u.name);}});});
test("DetailPanel: weeklyBreakdown guard safe",()=>{USERS.forEach(u=>{try{var h=u.weeklyBreakdown&&u.weeklyBreakdown.length>0;}catch(e){throw new Error("weeklyBreakdown guard: "+u.name);}});});
test("DetailPanel: clarityPeriods guard safe",()=>{USERS.forEach(u=>{try{var h=u.clarityPeriods&&u.clarityPeriods.length>0;}catch(e){throw new Error("clarityPeriods guard: "+u.name);}});});
test("DetailPanel: diff/pct no NaN",()=>{USERS.forEach(u=>{var diff=Number(u.scheduled)-Number(u.entered);var pct=u.scheduled?Math.round((u.entered/u.scheduled)*100):0;if(isNaN(diff))throw new Error("diff NaN: "+u.name);if(isNaN(pct))throw new Error("pct NaN: "+u.name);});});
test("DetailPanel: hooks order - early return after hooks",()=>{var hooks=0;function panel(uid,users){hooks++;hooks++;hooks++;var user=users.find(u=>u.id===uid)||null;if(!user)return null;return user;}var b=hooks;panel("missing",USERS);if(hooks-b!==3)throw new Error("Hook count wrong for null case");var b2=hooks;panel(USERS[0].id,USERS);if(hooks-b2!==3)throw new Error("Hook count wrong for valid case");});
test("DetailPanel: projectSummary on empty history",()=>{USERS.forEach(u=>{try{var m={};(u.history||[]).forEach(r=>{if(!m[r.projectCode])m[r.projectCode]={s:0};m[r.projectCode].s+=r.scheduled;});}catch(e){throw new Error("projectSummary: "+u.name);}});});

section("6. Dashboard Tab Safety");
test("Dashboard: stat counts sum to total",()=>{var b=USERS.filter(u=>u.dataSource==="Both").length,i=USERS.filter(u=>u.dataSource==="IBM only").length,c=USERS.filter(u=>u.dataSource==="Clarity only").length;if(b+i+c!==USERS.length)throw new Error("Counts don't sum");});
test("Dashboard: totalSched reduce safe",()=>{try{USERS.reduce((s,u)=>s+(Number(u.scheduled)||0),0);}catch(e){throw e;}});
test("Dashboard: totalActual reduce safe",()=>{try{USERS.reduce((s,u)=>s+(Number(u.entered)||0),0);}catch(e){throw e;}});
test("Dashboard: monthlyHours reduce safe",()=>{try{USERS.reduce((s,u)=>s+((u.monthlyHours||{})["March-2026"]||Number(u.entered)||0),0);}catch(e){throw e;}});
test("Dashboard: deptMap forEach safe",()=>{try{var m={};USERS.forEach(u=>{var d=u.dept||"Unknown";if(!m[d])m[d]={s:0};m[d].s+=Number(u.scheduled)||0;});}catch(e){throw e;}});
test("Dashboard: pieData covers all records",()=>{var t=0;USERS.forEach(u=>{var s=getStatus(u);t++;});if(t!==USERS.length)throw new Error("pieData count wrong");});

section("7. Full E2E Flow");
test("E2E: import→fix→records no crash",()=>{var m=mergeRecords(IBM_RAW,CLARITY_RAW,{});var a=m.matched.concat(m.ibmOnly).concat(m.clarityOnly);var u=handleImport(a);var ibmList=u.filter(x=>x.dataSource==="IBM only");var linked=ibmList.slice(0,2).map((x,i)=>({ibmId:x.id,clarityId:SAVED_CLARITY[i].id}));var fixed=applyLinks(u,linked,SAVED_CLARITY);var err=null;try{filterUsers(fixed);}catch(e){err=e;}if(err)throw err;filterUsers(fixed).forEach((x,i)=>{if(!x||!x.name||!x.id)throw new Error("E2E filtered["+i+"] invalid");});});
test("E2E: unique IDs after fix",()=>{var ibm=USERS.find(u=>u.dataSource==="IBM only");if(!ibm)return;var r=applyLinks(USERS,[{ibmId:ibm.id,clarityId:SAVED_CLARITY[0].id}],SAVED_CLARITY);var ids=r.map(u=>u.id);if(new Set(ids).size!==ids.length)throw new Error("Duplicate IDs after applyLinks");});
test("E2E: count correct after 2 links",()=>{var co=USERS.filter(u=>u.dataSource==="Clarity only");var io=USERS.filter(u=>u.dataSource==="IBM only");var n=Math.min(co.length,io.length,2);if(!n)return;var savedCl=co.slice(0,n).map(u=>({id:u.id,name:u.name,clarityName:u.clarityName||u.name,entered:u.entered||0,monthlyHours:u.monthlyHours||{},timesheetStatus:u.timesheetStatus||"",resourceManager:u.resourceManager||"",approvedBy:"",resourceActive:"",periods:u.periods||[],clarityPeriods:u.clarityPeriods||[]}));var linked=io.slice(0,n).map((u,i)=>({ibmId:u.id,clarityId:savedCl[i].id}));var r=applyLinks(USERS,linked,savedCl);if(r.length!==USERS.length-n)throw new Error("Expected "+(USERS.length-n)+" got "+r.length);if(!r.every(u=>u&&u.id&&u.name))throw new Error("Invalid records after fix");});
test("E2E: manual match override safe",()=>{var manual={[normalizeName("Ayan Das")]:normalizeName("Das, Sayan")};var m=mergeRecords(IBM_RAW,CLARITY_RAW,manual);var u=handleImport(m.matched.concat(m.ibmOnly).concat(m.clarityOnly));var r=filterUsers(u);if(!r.every(x=>x&&x.name))throw new Error("Invalid after manual match");});
test("E2E: 100 user stress test",()=>{var ibm=Array.from({length:100},(_,i)=>({rawName:"User "+i,normalizedName:normalizeName("User "+i),scheduledHours:80,wbsId:"T",workitems:[],claimMonths:[],ibmMonthlyHours:{},weeklyBreakdown:[],dayHours:{},country:"India",billingCode:"B",talentId:"T"+i}));var cl=Array.from({length:60},(_,i)=>({rawName:"User "+i,normalizedName:normalizeName("User "+i),actualHours:80,monthlyHours:{},timesheetStatus:"Posted",resourceManager:"Mgr",periods:[]}));var err=null;try{var m=mergeRecords(ibm,cl,{});var a=m.matched.concat(m.ibmOnly).concat(m.clarityOnly);var u=handleImport(a);filterUsers(u);}catch(e){err=e;}if(err)throw err;});

section("8. Edge & Null Safety");
test("Edge: empty import",()=>{var u=handleImport([]);if(u.length!==0)throw new Error("Expected 0");if(filterUsers(u).length!==0)throw new Error("Expected 0 filtered");});
test("Edge: undefined monthlyHours in reduce",()=>{var u=USERS.map(x=>Object.assign({},x,{monthlyHours:undefined}));try{u.reduce((s,x)=>s+((x.monthlyHours||{})["March-2026"]||0),0);}catch(e){throw e;}});
test("Edge: getStatus all combinations",()=>{[{s:0,e:0},{s:100,e:0},{s:100,e:100},{s:100,e:120},{s:null,e:null},{s:undefined,e:undefined}].forEach((c,i)=>{try{getStatus({scheduled:c.s,entered:c.e});}catch(e){throw new Error("getStatus case "+i+": "+e.message);}});});
test("Edge: getSeverity all combinations",()=>{[{s:0,e:0},{s:100,e:0},{s:100,e:30},{s:100,e:80},{s:100,e:100},{s:100,e:120},{s:null,e:null}].forEach((c,i)=>{try{getSeverity({scheduled:c.s,entered:c.e});}catch(e){throw new Error("getSeverity case "+i+": "+e.message);}});});
test("Edge: over-reported severity=0",()=>{expect(getSeverity({scheduled:100,entered:120})).toBe(0);});
test("Edge: name sort with null names",()=>{var u=[{name:"Z"},{name:null},{name:"A"},{name:undefined}];try{u.slice().sort((a,b)=>(a.name||"").localeCompare(b.name||""));}catch(e){throw e;}});
test("Edge: applyLinks all IBM-only no clarity",()=>{var u=handleImport(mergeRecords(IBM_RAW,[],{}).ibmOnly);try{applyLinks(u,[],SAVED_CLARITY);}catch(e){throw e;}});

console.log("\n"+"=".repeat(70));
console.log(" INTEGRATION TEST RESULTS");
console.log("=".repeat(70));
const grouped={};results.forEach(r=>{if(!grouped[r.s])grouped[r.s]=[];grouped[r.s].push(r);});
Object.entries(grouped).forEach(([sec,tests])=>{var gP=tests.filter(t=>t.status==="PASS").length,gF=tests.filter(t=>t.status==="FAIL").length;console.log("\n"+(gF===0?"✅":"❌")+" "+sec+" ("+gP+"/"+tests.length+")");tests.forEach(t=>{if(t.status==="FAIL")console.log("  ✗ "+t.name+"\n      → "+t.error);else console.log("  ✓ "+t.name);});});
console.log("\n"+"=".repeat(70));
console.log(" TOTAL: "+passed+"/"+total+" passed | "+failed+" failed");
console.log("=".repeat(70)+"\n");
if(failed>0)process.exit(1);
